### ISSUE TITLE
Catch connection error and display help

### ISSUE THREAD

**Issue by Arn-O** [Arn-O/py-xbmc-remote-controller#24]
When the Kodi server is not reachable, a connection refused message is displayed:

```
Traceback (most recent call last):
  File "pyxbmc.py", line 645, in <module>
    main()
  File "pyxbmc.py", line 642, in main
    remote_controller.cmdloop()
  File "/usr/lib64/python2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "pyxbmc.py", line 482, in preloop
    sys_name = system_friendly_name(self.xbmc_ip, self.xbmc_port)
  File "pyxbmc.py", line 298, in system_friendly_name
    ret = call_api(ip, port, command)
  File "pyxbmc.py", line 46, in call_api
    s.connect((ip, port))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
```

The error can be caught and an explanation of how to activate the remote control can be displayed.

**Comment by Arn-O** [comment]
The connection to the Kodi server has to be checked for all functions that require it:

+ ``songs_search`` the connection is not required and the user should be free to use this function without the availability of the Kodi server
+ ``play_pause`` this function cannot be used without the Kodi server, the hard error mentioned above should be prevented, a soft error will be displayed.

Moreover, when the Kodi server is unreachable, a message should describe the prerequisites on the Kodi side:

http://kodi.wiki/view/Webserver#Enabling_the_webserver

Note that this issue is related to the offline mode as described in the issue #66, which should be implemented before this one.
